---
 - name: install httpd
   yum: name={{ item }} state=installed disable_gpg_check=yes
   with_items:
    - httpd
    - mariadb-server
    - mariadb
   notify: service_restart
   #notify: httpd_restart
   #notify: mariadb_restart

 - name: install php
   yum: name={{ item }} state=installed
   with_items:
    - php
    - php-mysql
    - php-pdo
    - php-gd
    - php-mbstring

 
